# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build
      run: ./gradlew assemble

    - name: Run App with Gradle
      run: ./gradlew runApp & # Run app in background

    - name: Wait
      run: sleep 10

    - name: Curl check
      run: curl localhost:4568/hello

    - name: Run Tests
      run: ./gradlew test

    - name: Publish test results
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: junit-results
        path: |
          build/reports/tests/*
          build/test-results/test/**/*.xml
        if-no-files-found: error
